/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.project;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import java.util.regex.Pattern;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author dan
 */
public class PharmacyProject extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyProject
     */
    public PharmacyProject() {
        initComponents();
    }

    public void ShowConfirmModal(String message) {
        JDialog newWindow = new JDialog((JFrame) null, "Confirmar la orden", true);
        newWindow.setSize(500, 200);
        newWindow.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        newWindow.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                newWindow.dispose();
            }
        });
        int screenWidth = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x = (screenWidth - newWindow.getWidth()) / 2;
        int y = (screenHeight - newWindow.getHeight()) / 2;
        newWindow.setLocation(x, y);

        newWindow.setLayout(new BorderLayout());
        JLabel label = new JLabel(message);
        label.setHorizontalAlignment(JLabel.CENTER);
        newWindow.add(label, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton confirmButton = new JButton("Confirmar");
        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                newWindow.dispose();
                DrugNameField.setText("");
                DrugTypeDropdown.setSelectedItem("");
                DrugQuantityField.setText("");
                CofarmaDistributorOption.setSelected(false);
                EmpsepharDistributorOption.setSelected(false);
                CemefarDistributorOption.setSelected(false);
                PrincipalBranchOption.setSelected(false);
                SecundariaBranchOption.setSelected(false);

                JDialog confirmed = new JDialog((JFrame) null, "¡Orden confirmada!", true);
                confirmed.setSize(300, 200);
                confirmed.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                confirmed.setLocation(x, y);
                confirmed.setLayout(new FlowLayout(FlowLayout.CENTER));
                JLabel confirmationLabel = new JLabel("¡Gracias por su compra!");
                confirmationLabel.setHorizontalAlignment(JLabel.CENTER);
                confirmed.add(confirmationLabel);
                confirmed.setVisible(true);
            }
        });

        JButton closeButton = new JButton("Cancelar");
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                newWindow.dispose();
            }
        });

        buttonPanel.add(confirmButton);
        buttonPanel.add(closeButton);

        newWindow.add(buttonPanel, BorderLayout.SOUTH);
        newWindow.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DrugNameField = new javax.swing.JTextField();
        DrugTypeDropdown = new javax.swing.JComboBox<>();
        DrugDistributorPanel = new javax.swing.JPanel();
        CofarmaDistributorOption = new javax.swing.JRadioButton();
        EmpsepharDistributorOption = new javax.swing.JRadioButton();
        CemefarDistributorOption = new javax.swing.JRadioButton();
        DrugBranchPanel = new javax.swing.JPanel();
        PrincipalBranchOption = new javax.swing.JCheckBox();
        SecundariaBranchOption = new javax.swing.JCheckBox();
        DrugQuantityField = new javax.swing.JFormattedTextField();
        ClearAllButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        ErrorPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ErrorDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Frame");

        jLabel1.setText("¡Bienvenido a tu farmacia en línea!");

        jLabel2.setText("Nombre del medicamento");

        jLabel3.setText("Tipo de medicamento");

        jLabel4.setText("Cantidad de medicamento");

        jLabel5.setText("Distribuidor");

        jLabel6.setText("Sucursal");

        DrugNameField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                DrugNameFieldCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        DrugNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugNameFieldActionPerformed(evt);
            }
        });
        DrugNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DrugNameFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DrugNameFieldKeyTyped(evt);
            }
        });

        DrugTypeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));

        CofarmaDistributorOption.setText("Cofarma");
        CofarmaDistributorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CofarmaDistributorOptionActionPerformed(evt);
            }
        });

        EmpsepharDistributorOption.setText("Empsephar");
        EmpsepharDistributorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpsepharDistributorOptionActionPerformed(evt);
            }
        });

        CemefarDistributorOption.setText("Cemefar");
        CemefarDistributorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CemefarDistributorOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DrugDistributorPanelLayout = new javax.swing.GroupLayout(DrugDistributorPanel);
        DrugDistributorPanel.setLayout(DrugDistributorPanelLayout);
        DrugDistributorPanelLayout.setHorizontalGroup(
            DrugDistributorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrugDistributorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CofarmaDistributorOption)
                .addGap(111, 111, 111)
                .addComponent(EmpsepharDistributorOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CemefarDistributorOption)
                .addContainerGap())
        );
        DrugDistributorPanelLayout.setVerticalGroup(
            DrugDistributorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrugDistributorPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DrugDistributorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CofarmaDistributorOption)
                    .addComponent(EmpsepharDistributorOption)
                    .addComponent(CemefarDistributorOption))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PrincipalBranchOption.setText("Principal");

        SecundariaBranchOption.setText("Secundaria");

        javax.swing.GroupLayout DrugBranchPanelLayout = new javax.swing.GroupLayout(DrugBranchPanel);
        DrugBranchPanel.setLayout(DrugBranchPanelLayout);
        DrugBranchPanelLayout.setHorizontalGroup(
            DrugBranchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrugBranchPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(PrincipalBranchOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(SecundariaBranchOption)
                .addGap(84, 84, 84))
        );
        DrugBranchPanelLayout.setVerticalGroup(
            DrugBranchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrugBranchPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(DrugBranchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrincipalBranchOption)
                    .addComponent(SecundariaBranchOption))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        ClearAllButton.setText("Limpiar");
        ClearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setText("Confirmar");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        ErrorDisplay.setColumns(20);
        ErrorDisplay.setRows(5);
        jScrollPane2.setViewportView(ErrorDisplay);

        javax.swing.GroupLayout ErrorPanelLayout = new javax.swing.GroupLayout(ErrorPanel);
        ErrorPanel.setLayout(ErrorPanelLayout);
        ErrorPanelLayout.setHorizontalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        ErrorPanelLayout.setVerticalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DrugTypeDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DrugNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DrugDistributorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DrugQuantityField)
                                    .addComponent(DrugBranchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(ClearAllButton)
                                .addGap(276, 276, 276)
                                .addComponent(ConfirmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE))))
                    .addComponent(ErrorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DrugNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DrugTypeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DrugQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrugDistributorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DrugBranchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addComponent(ErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearAllButton)
                    .addComponent(ConfirmButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrugNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugNameFieldActionPerformed

    }//GEN-LAST:event_DrugNameFieldActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        var drugName = DrugNameField.getText().trim();
        var drugType = DrugTypeDropdown.getSelectedItem();
        var drugQuatity = 0;
        ArrayList<String> drugBranches = new ArrayList<>();
        var drugDistributor = "";
        ArrayList<String> ErrorMessages = new ArrayList<>();

        // Set drug quantity
        if (DrugQuantityField.getText().trim().matches("\\d+") && DrugQuantityField.getText().trim().length() < 10) {
            drugQuatity = Integer.parseInt(DrugQuantityField.getText().trim());
        }

        // Set distributor
        if (CofarmaDistributorOption.isSelected()) {
            drugDistributor = CofarmaDistributorOption.getText();
        } else if (EmpsepharDistributorOption.isSelected()) {
            drugDistributor = EmpsepharDistributorOption.getText();
        } else if (CemefarDistributorOption.isSelected()) {
            drugDistributor = CemefarDistributorOption.getText();
        }

        // Set branch
        if (PrincipalBranchOption.isSelected()) {
            drugBranches.add(PrincipalBranchOption.getText());
        }
        if (SecundariaBranchOption.isSelected()) {
            drugBranches.add(SecundariaBranchOption.getText());
        }

        // Check for errors and show alerts
        if (drugName.isEmpty()) {
            DrugNameField.setBackground(Color.RED);
            ErrorMessages.add("CODE1: No se ha seleccionado nombre del medicamento o no es alfanumérico.");
        } else {
            if (Pattern.matches("^[a-zA-Z0-9]+$", drugName)) {
                DrugNameField.setBackground(Color.WHITE);
                ErrorMessages.removeIf(item -> item.contains("CODE1"));
            } else {
                DrugNameField.setBackground(Color.RED);
                ErrorMessages.add("CODE1: No se ha seleccionado nombre del medicamento o no es alfanumérico.");
            }
        }

        if (drugType.toString().isEmpty()) {
            DrugTypeDropdown.setBackground(Color.RED);
            ErrorMessages.add("CODE2: No se ha seleccionado tipo del medicamento.");
        } else {
            DrugTypeDropdown.setBackground(Color.WHITE);
            ErrorMessages.removeIf(item -> item.contains("CODE2"));
        }

        if (drugQuatity <= 0) {
            DrugQuantityField.setBackground(Color.RED);
            ErrorMessages.add("CODE3: No se ha seleccionado cantidad del medicamento o no es un número válido.");
        } else {
            DrugQuantityField.setBackground(Color.WHITE);
            ErrorMessages.removeIf(item -> item.contains("CODE3"));
        }

        if (drugDistributor.isEmpty()) {
            DrugDistributorPanel.setBorder(new LineBorder(Color.RED, 2));
            ErrorMessages.add("CODE4: No se ha seleccionado distribuidor del medicamento");
        } else {
            DrugDistributorPanel.setBorder(new LineBorder(Color.WHITE, 0));
            ErrorMessages.removeIf(item -> item.contains("CODE4"));
        }

        if (drugBranches.isEmpty()) {
            DrugBranchPanel.setBorder(new LineBorder(Color.RED, 2));
            ErrorMessages.add("CODE5: No se ha sucursal para envío del medicamento");
        } else {
            DrugBranchPanel.setBorder(new LineBorder(Color.WHITE, 0));
            ErrorMessages.removeIf(item -> item.contains("CODE5"));
        }

        if (!ErrorMessages.isEmpty()) {
            ErrorDisplay.setText("");
            for (String item : ErrorMessages) {
                ErrorDisplay.append(item + "\n");
            }
            ErrorPanel.setVisible(true);
        } else {
            ErrorPanel.setVisible(false);
            ErrorDisplay.setText("");

            String orderMessage = String.format("%s unidades del %s %s", drugQuatity, drugType, drugName);

            ShowConfirmModal(orderMessage);
        }


    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void DrugNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DrugNameFieldKeyTyped

    }//GEN-LAST:event_DrugNameFieldKeyTyped

    private void DrugNameFieldCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DrugNameFieldCaretPositionChanged

    }//GEN-LAST:event_DrugNameFieldCaretPositionChanged

    private void DrugNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DrugNameFieldKeyPressed

    }//GEN-LAST:event_DrugNameFieldKeyPressed

    private void CofarmaDistributorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CofarmaDistributorOptionActionPerformed
        EmpsepharDistributorOption.setSelected(false);
        CemefarDistributorOption.setSelected(false);
    }//GEN-LAST:event_CofarmaDistributorOptionActionPerformed

    private void EmpsepharDistributorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpsepharDistributorOptionActionPerformed
        CofarmaDistributorOption.setSelected(false);
        CemefarDistributorOption.setSelected(false);
    }//GEN-LAST:event_EmpsepharDistributorOptionActionPerformed

    private void CemefarDistributorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CemefarDistributorOptionActionPerformed
        CofarmaDistributorOption.setSelected(false);
        EmpsepharDistributorOption.setSelected(false);
    }//GEN-LAST:event_CemefarDistributorOptionActionPerformed

    private void ClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllButtonActionPerformed

        DrugNameField.setText("");
        DrugTypeDropdown.setSelectedItem("");
        DrugQuantityField.setText("");
        CofarmaDistributorOption.setSelected(false);
        EmpsepharDistributorOption.setSelected(false);
        CemefarDistributorOption.setSelected(false);
        PrincipalBranchOption.setSelected(false);
        SecundariaBranchOption.setSelected(false);
    }//GEN-LAST:event_ClearAllButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyProject().setVisible(true);
                ErrorPanel.setVisible(false);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton CemefarDistributorOption;
    private javax.swing.JButton ClearAllButton;
    public static javax.swing.JRadioButton CofarmaDistributorOption;
    public static javax.swing.JButton ConfirmButton;
    private javax.swing.JPanel DrugBranchPanel;
    private javax.swing.JPanel DrugDistributorPanel;
    public static javax.swing.JTextField DrugNameField;
    public static javax.swing.JFormattedTextField DrugQuantityField;
    public static javax.swing.JComboBox<String> DrugTypeDropdown;
    public static javax.swing.JRadioButton EmpsepharDistributorOption;
    private javax.swing.JTextArea ErrorDisplay;
    public static javax.swing.JPanel ErrorPanel;
    public static javax.swing.JCheckBox PrincipalBranchOption;
    public static javax.swing.JCheckBox SecundariaBranchOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
